// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD4aXwz5iewXddvvx-Dc4E9j0v5Os9LLA',
    appId: '1:958852572177:web:6398a55d3fa4e4e9153db0',
    messagingSenderId: '958852572177',
    projectId: 'cloudanalytics-d4455',
    authDomain: 'cloudanalytics-d4455.firebaseapp.com',
    storageBucket: 'cloudanalytics-d4455.appspot.com',
    measurementId: 'G-5XB312TJKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiZtuiiNrwd0DFN6zJrKIuEo_DNW5-FQQ',
    appId: '1:958852572177:android:615d9fdcd18a1026153db0',
    messagingSenderId: '958852572177',
    projectId: 'cloudanalytics-d4455',
    storageBucket: 'cloudanalytics-d4455.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZb54oKcSWJdNbxpgKkFbDojWehh6YRPc',
    appId: '1:958852572177:ios:03c9af08d959ea66153db0',
    messagingSenderId: '958852572177',
    projectId: 'cloudanalytics-d4455',
    storageBucket: 'cloudanalytics-d4455.appspot.com',
    iosClientId: '958852572177-617rj6uelktqk0412qkqfcehjvdnt5eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZb54oKcSWJdNbxpgKkFbDojWehh6YRPc',
    appId: '1:958852572177:ios:03c9af08d959ea66153db0',
    messagingSenderId: '958852572177',
    projectId: 'cloudanalytics-d4455',
    storageBucket: 'cloudanalytics-d4455.appspot.com',
    iosClientId: '958852572177-617rj6uelktqk0412qkqfcehjvdnt5eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudAnalytics',
  );
}
